apiVersion: v1
kind: Service
metadata:
  name: members-svc
spec:
  selector:
    app: members-svc
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
   name: members-svc-config
data:
 uri: mongodb+srv://admin:root@cluster0.vwpz2pv.mongodb.net/members_db?retryWrites=true&w=majority
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: members-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: members-svc
  template:
    metadata:
      labels:
        app: members-svc
    spec:
      containers:
        - name: members-svc
          image: gcr.io/wonderl4nd-project/members-svc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: members-svc-config  
                  key: uri